export const translations = {
  zh: {
    // 导航
    home: '首页',
    about: '关于',
    docs: '文档',
    signIn: '登录',
    
    // 英雄区
    heroTitle: '用AI创建\n吉卜力风格的梦幻艺术',
    heroDescription: '只需输入提示词，即可生成宫崎骏风格的精美图像',
    promptPlaceholder: '输入提示词，例如：森林中的小屋，阳光透过树叶',
    startCreating: '开始创作',
    
    // 图像生成器
    generate: '生成',
    download: '下载',
    
    // 图库
    galleryTitle: '图库展示',
    galleryDescription: '欣赏由我们的 AI 生成的精选吉卜力风格图像',
    
    // 使用说明
    howToUseTitle: '如何使用',
    howToUseDescription: '按照以下简单步骤，开始创建您的吉卜力风格图像',
    step1Title: '输入提示词',
    step1Description: '在输入框中输入您想要生成的图像描述',
    step2Title: '点击生成',
    step2Description: '点击生成按钮，等待 AI 创建您的图像',
    step3Title: '下载或分享',
    step3Description: '下载生成的图像或分享到社交媒体',
    
    // 页脚
    madeWith: '用爱制作',
    
    // 语言
    language: '语言',
    chinese: '中文',
    english: '英文',
    japanese: '日语',
  },
  en: {
    // 导航
    home: 'Home',
    about: 'About',
    docs: 'Docs',
    signIn: 'Sign in',
    
    // 英雄区
    heroTitle: 'Create Ghibli-style\nDream Art with AI',
    heroDescription: 'Just enter a prompt to generate beautiful Miyazaki-style images',
    promptPlaceholder: 'Enter a prompt, e.g.: A cottage in the forest, sunlight through leaves',
    startCreating: 'Start Creating',
    
    // 图像生成器
    generate: 'Generate',
    download: 'Download',
    
    // 图库
    galleryTitle: 'Gallery',
    galleryDescription: 'Enjoy curated Ghibli-style images generated by our AI',
    
    // 使用说明
    howToUseTitle: 'How to Use',
    howToUseDescription: 'Follow these simple steps to start creating your Ghibli-style images',
    step1Title: 'Enter a Prompt',
    step1Description: 'Type your image description in the input box',
    step2Title: 'Click Generate',
    step2Description: 'Click the Generate button and wait for the AI to create your image',
    step3Title: 'Download or Share',
    step3Description: 'Download the generated image or share it on social media',
    
    // 页脚
    madeWith: 'Made with love',
    
    // 语言
    language: 'Language',
    chinese: 'Chinese',
    english: 'English',
    japanese: 'Japanese',
  },
  ja: {
    // 导航
    home: 'ホーム',
    about: '概要',
    docs: '資料',
    signIn: 'ログイン',
    
    // 英雄区
    heroTitle: 'AIでジブリ風の\n夢のようなアートを作成',
    heroDescription: 'プロンプトを入力するだけで、宮崎駿スタイルの美しい画像を生成できます',
    promptPlaceholder: 'プロンプトを入力してください（例：森の中の小さな家、木漏れ日）',
    startCreating: '作成を開始',
    
    // 图像生成器
    generate: '生成',
    download: 'ダウンロード',
    
    // 图库
    galleryTitle: 'ギャラリー',
    galleryDescription: '私たちのAIが生成した厳選されたジブリ風画像をお楽しみください',
    
    // 使用说明
    howToUseTitle: '使用方法',
    howToUseDescription: 'これらの簡単なステップに従って、ジブリ風の画像の作成を始めましょう',
    step1Title: 'プロンプトを入力',
    step1Description: '入力ボックスに画像の説明を入力します',
    step2Title: '生成をクリック',
    step2Description: '生成ボタンをクリックし、AIが画像を作成するのを待ちます',
    step3Title: 'ダウンロードまたは共有',
    step3Description: '生成された画像をダウンロードするか、ソーシャルメディアで共有します',
    
    // 页脚
    madeWith: '愛を込めて作られました',
    
    // 语言
    language: '言語',
    chinese: '中国語',
    english: '英語',
    japanese: '日本語',
  }
}; 